RandomForestClassifier:
  n_estimators: 50
  random_state: 42
  max_depth: 15
  min_samples_split: 2
  min_samples_leaf: 1
  class_weight: balanced

RandomForestRegressor:
  n_estimators: 50
  random_state: 42
  max_depth: 15
  min_samples_split: 2
  min_samples_leaf: 1
